# Generated by Django 5.0.2 on 2024-02-17 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="department",
            new_name="floor",
        ),
    ]
